- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: demo
    location: northeurope
    storage_type: Standard_LRS
    os_disk_type: StandardSSD_LRS
    vm_size: Standard_B1ms
    admin_username: demouser
    ssh_pub_key:
    image: rhel8-golden-image
    vm_prefix: azure
    num_vm: 1

  tasks:
  - name: Create the resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ resource_group }}-vnet"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: default
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ resource_group }}-vnet"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ vm_prefix }}{{ num_vm }}-ip"
    with_sequence: start=1 end={{num_vm|int}}
    register: publicip

  - name: Show Public IP address
    debug:
      msg: "{{ publicip.results.state.ip_address }}"
