- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: demo
    location: northeurope
    vm_name: demo-vm

  tasks:
  - name: Create the resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ resource_group }}"-vnet
      address_prefixes: "10.1.0.0/24"
