- name: Delete Azure demo environment
  hosts: localhost
  connection: local
  vars:
    resource_group: demo

  tasks:
  - name: Delete the demo resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      force_delete_nonempty: yes
      state: absent
