- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:

  tasks:
  - include_role:
      name: ansible-role-azure-vm

  - name: make public ip var available for other playbooks
    set_stats:
      data:
        db_public_ip: "{{ public_ips[0] }}"
    when: azure_vm_vm_prefix == "db"
