- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    public_ip_var_name:

  tasks:
  - include_role:
      name: ansible-role-azure-vm

  - name: make public ip var available for other playbooks
    set_stats:
      "{{ public_ip_var_name }}": "{{ public_ips }}"
