- src: https://github.com/pgustafs/ansible-role-rhsm.git
  scm: git
- src: https://github.com/pgustafs/ansible-role-openscap.git
  scm: git
- src: https://github.com/pgustafs/ansible-role-azure-vm.git
  scm: git
- redhatinsights.insights-client
